### SIGNUP
POST https://ticketing.dev/api/users/signup
Content-Type: application/json

{
    "email":"killer@asdf.com",
    "password":"test1234"
}

### SIGN IN
POST http://ticketing.dev/api/users/signin
Content-Type: application/json

{
    "email":"asdf@asdf.com",
    "password":"sss"
}