### SIGNUP
POST https://ticketing.dev/api/users/signup
Content-Type: application/json

{
    "email":"asdfasddsaf@asdf.com",
    "password":"test1234"
}


### NOT FOUND

GET http://ticketing.dev/api/users/ggg