### SIGNUP
POST http://ticketing.dev/api/users/signup
Content-Type: application/json

{
    "email":"test@asdf.com",
    "password":"test1234"
}


### NOT FOUND

GET http://ticketing.dev/api/users/ggg